sudo: true

language: php
php:
  - 7.1.9

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

services:
  - mysql

before_install:
  - nvm install 8.9
  - nvm use 8.9

script:
  - vendor/bin/phpunit --colors
