sudo: true

language: php
php:
  - 7.1.11

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

addons:
  apt:
    packages:
      - nasm

before_install:
  - nvm use v8.9
  - composer install
  - npm install
  - cp -uv .env.example .env
  - php artisan key:generate

script:
  - npm run dev
  - vendor/bin/phpcs --extensions='php' --ignore='*.blade.php,bootstrap,vendor,node_modules,storage,public,database,_ide_helper.php' --standard='PSR2' .
  - vendor/bin/phpunit --colors
